FROM ghcr.io/isaric/python-opencv-docker:python-3.10-opencv-4.8.0-arm64
  
ENV DLIB_VERSION=19.24
ENV DLIB=dlib-${DLIB_VERSION}

RUN wget http://dlib.net/files/${DLIB}.tar.bz2
RUN tar xvf ${DLIB}.tar.bz2
RUN mkdir ${DLIB}/build
RUN cmake ${DLIB}
RUN cmake --build .
RUN sudo make install
RUN sudo ldconfig
RUN pkg-config ${DLIB} --libs --cflags dlib-1
